
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Volume extends javax.swing.JFrame {

    /**
     * Creates new form Volume
     */
    public Volume() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        skubus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        volkubus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tbalok = new javax.swing.JTextField();
        pbalok = new javax.swing.JTextField();
        lbalok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        rbola = new javax.swing.JTextField();
        htbola = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        jLabel1.setText("Program Penghitung Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 470, 40);

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 255));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 20, 150, 40);
        jPanel2.add(skubus);
        skubus.setBounds(30, 60, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(190, 64, 30, 20);

        volkubus.setText("Volume");
        volkubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volkubusActionPerformed(evt);
            }
        });
        jPanel2.add(volkubus);
        volkubus.setBounds(30, 110, 90, 40);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(null);

        jLabel2.setText("Tinggi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 120, 40, 30);

        jLabel3.setText("Panjang");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 40, 50, 30);

        jLabel4.setText("Lebar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 80, 50, 30);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 170, 90, 40);

        tbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbalokActionPerformed(evt);
            }
        });
        jPanel1.add(tbalok);
        tbalok.setBounds(170, 120, 60, 30);

        pbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbalokActionPerformed(evt);
            }
        });
        jPanel1.add(pbalok);
        pbalok.setBounds(170, 40, 60, 30);
        jPanel1.add(lbalok);
        lbalok.setBounds(170, 80, 60, 30);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 120, 30, 30);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 40, 30, 30);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 80, 30, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel3.setBackground(new java.awt.Color(239, 137, 137));
        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-Jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 20, 180, 30);
        jPanel3.add(rbola);
        rbola.setBounds(10, 50, 170, 30);

        htbola.setText("Hitung");
        htbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htbolaActionPerformed(evt);
            }
        });
        jPanel3.add(htbola);
        htbola.setBounds(10, 93, 90, 40);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(190, 50, 13, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 60, 454, 284);

        jPanel4.setBackground(new java.awt.Color(248, 246, 166));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 450, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbalokActionPerformed

    private void pbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pbalokActionPerformed

    private void volkubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volkubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(skubus.getText());
        int hasil = sisi*sisi*sisi;
        try {
            JOptionPane.showMessageDialog(null, "Volume Kubus = "+hasil, "luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e, "Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_volkubusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(pbalok.getText());
        lebar = Integer.parseInt(lbalok.getText());
        tinggi = Integer.parseInt(tbalok.getText());
        int hasil = panjang*lebar*tinggi;
        try {
            JOptionPane.showMessageDialog(null, "Volume Balok = "+hasil, "luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e, "Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void htbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htbolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(rbola.getText());
        float hasil = (float) (4*3*3.14*jari*jari*jari);
        try {
            JOptionPane.showMessageDialog(null, "Volume Bola = "+hasil, "luas", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e, "Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_htbolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton htbola;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lbalok;
    private javax.swing.JTextField pbalok;
    private javax.swing.JTextField rbola;
    private javax.swing.JTextField skubus;
    private javax.swing.JTextField tbalok;
    private javax.swing.JButton volkubus;
    // End of variables declaration//GEN-END:variables
}
